version: "3.5"

services:
   web:
      build: ./
      command: gunicorn -b 0.0.0.0:8000 -k eventlet -w 1 --reload app:app
      restart: always

   nginx:
      build: ./compose/nginx
      volumes:
         - ./compose/nginx/ssl:/usr/share/nginx/ssl # 挂载ssl证书目录
      depends_on:
         - web
      restart: always
      ports:
         - "80:80"
      # environment:
      #    - VIRTUAL_HOST=957tw.com,www.957tw.com
      #    - VIRTUAL_NETWORK=nginx-proxy
      #    - VIRTUAL_PORT=80
         # - LETSENCRYPT_HOST=957tw.com,www.957tw.com
         # - LETSENCRYPT_EMAIL=your_mail@gmail.com